version: "3.1"
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    network_mode: bridge
    privileged: true
    volumes:
      - ./logs:/var/log/nginx/
      - ./conf.d:/etc/nginx/conf.d/
      - ./cert:/etc/nginx/cert/
    ports:
      - 80:80
      - 443:443
